# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
# Default values for ranger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  egeria:
    repository: planetf1/egeria-standalone
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""


kafka:
  external:
    enabled: true
    type: NodePort

# Network configuration for Egeria itself
service:
  #LoadBalancer is another option (not for IBM Cloud free cluster)
  type: NodePort



