# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
name: vdc
description: Egeria VDC Environment 
version: 0.1.4
keywords:
  - apache-ranger, ranger, security, odpi, egeria, open-metadata,vdc, virtualization
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Nigel Jones
    email: nigel.l.jones+gh@gmail.com
