---

# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# Network configuration
# note that load balancer configuration tends to be cloud-specific
# So review the templates/loadbalancer* files for any
# required updates

service:
  #LoadBalancer is another option (not for IBM Cloud free cluster)
  # ClusterIP is recommended for IBMCloud - and enable ingress below
  # NodePort will work ok in other environments, including IBM ICP, but note that the ports may
  # well be non standard and services will be at http://<external address of a workernode>:<randomport>
  # Review output from 'kubectl get services' to see the external port used
  type: NodePort
  externalName: default.svc.cluster.local

  loadbalancer:
    enabled: false
    iptype: public
    publicip: <undefined>
  # Currently IBMCloud is the only supported setting, and enabled additional Ingress rules. Comment out for other platforms

  ingress:
    # Update this with your own domain
    enabled: false
    externaldomain: egeriadev.eu-gb.containers.appdomain.cloud
    cloudservice: IBMCloud

  # If type is NodePort, these are the ports we will request - but if not free, another will be allocated
  # and then things may not work externally. LoadBalancer & Ingress are recommended if possible.
  # Ports are required to be in the range 30000-32767 for IBM Cloud
  nodeport:
    egeria: 30080
    atlas: 31000
    ibmigc: 32446
    igcproxy: 30081
    gaian: 30414
    postgresql: 30432
    ui: 30443
    ranger: 32080
    rangersecure: 30182
    # Set this to address of one of the local nodes - public IP
    omrsmonitor: 31080
    externalip: 10.10.1.30
    # KAFKA is not exposed externally (issues in chart, complexity)

# Debug support for Egeria - set to true to enable JVM debug for Egeria images on port 5005
debug:
  egeriaJVM: false

# Logging level - affects all spring components by setting LOG_LEVEL_ROOT. Default to no DEBUG - Auditlog only
logging:
  level: NONE


# The following section defines all of the DOCKER images being used by this
# chart. Normally they should be left as is, but are exposed here in case the
# user wishes to extend.
image:
  ranger:
    repository: localhost:5000/odpi/ranger-admin-egeriavdc
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  mariadb:
    repository: mariadb
    tag: latest
    pullPolicy: Always

  egeria:
    repository: localhost:5000/odpi/egeria
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  gaian:
    repository: localhost:5000/odpi/gaian-egeriavdc
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  atlas:
    repository: localhost:5000/odpi/apache-atlas
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  kafkamonitor:
    repository: localhost:5000/odpi/kafka-monitor-egeriavdc
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  postgresql:
    repository: postgres
    tag: alpine
    pullPolicy: IfNotPresent

  omrsmonitor:
    repository: localhost:5000/odpi/omrsmonitor-egeriavdc
    tag: 1.1-SNAPSHOT
    pullPolicy: Always

  # NOTE: this image is only used if the ibmigc.external is set to false; otherwise it is ignored and
  # the k8s-external, pre-existing environment defined under ibmigc... is used
  ibmigc:
    repository: localhost:5000/ibm/infosvr
    tag: v11.7.0.2
    pullPolicy: IfNotPresent

  configure:
    repository: localhost:5000/odpi/egeria-configure
    tag: 1.1-SNAPSHOT
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

# Set 'use' to true to use your local repository rather than Egeria's (remote) master git repository
# (When set to true, also provide the absolute path to your local repository)
localRepo:
  use: true
  location: /Users/cgrote/Developer/git-repos/forks/odpi/egeria

# Whether to use a k8s cluster-internal Kafka or an external one -- if using internal,
# see 'cp-kafka' below for config options
kafka:
  internal:
    enabled: true
  external:
    hostname: ""
    ip: ""
    port: ""

# The demo can use an IBM IGC environment.
# Set external to "true" to use a pre-existing IBM IGC environment (outside your k8s cluster),
# in which case, also provide the hostname, IP address and port number for the domain tier
# NOTE: remember to also update the IBMIGC_ENDPOINT and IBMIGC_KAFKA_ENDPOINT in configmap!
ibmigc:
  enabled: false
  internal:
    enabled: true
  external:
    hostname: ""
    ip: ""
    port: ""

# When using the k8s-internal Kafka (from Confluent), enable auto-topic creation
# (for full options, see: https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-kafka)
cp-kafka:
  brokers: 1
  configurationOverrides:
    auto.create.topics.enable: true
  prometheus:
    jmx:
      enabled: false

# When using the k8s-internal Kafka (from Confluent), configure Zookeeper options
# (for full options, see: https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-zookeeper)
cp-zookeeper:
  servers: 1
  prometheus:
    jmx:
      enabled: false

# For the Confluent kafka chart there are many additional components
# that we don't need -- so they are removed here
cp-schema-registry:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-ksql-server:
  enabled: false

# Open LDAP configuration
openldap:
  adminPassword: passw0rd
  configPassword: passw0rd
  servicePort: 389
