---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

all:
  vars:
    # ansible_user: 
    # ansible_connection: local
    # ansible_ssh_private_key_file: 
  children:
    omagserver1:
      hosts:
        egeriadt01: 
      vars:
        app_port: 8080
        app_host: localhost
        app_name: egeria_omas
        app_version: 1.6-SNAPSHOT
        app_version_suffix: "{{ app_version }}"
        app_extra_libs:
        app_configs:
        admin_omag_server_config:
          omas-server:
            mode: server-chassis
            url: "http://{{ app_host }}:{{ app_port }}"
            user: admin
            cohort: mycohort
            cohort_topic: mytopic
            consumer: kafkaserver:9092
            producer: kafkaserver:9092
            auditlog_destination: slf4j
            auditlog_severity: []
        admin_omag_repo_config:
          omas-server:
            mode: local-graph-repository
        admin_omag_access_services_config:
          omas-server:
            # all:
            asset-catalog:
              body: 
                supportedTypesForSearch:
                  - Asset
                  - RelationalColumn 
        admin_omag_server_startup:
        - omas-server
       
      