---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
 
- name: "Configure servers"
  include: server.yml config={{ item }}
  with_dict: "{{ admin_omag_server_config }}"
  when: admin_omag_server_config is defined 

- name: "Configure repositories"
  include: repository.yml config={{ item }}
  with_dict: "{{ admin_omag_repo_config | default({}, true) }}"
  when: admin_omag_repo_config is defined

- name: "Enable access services"
  include: access-service.yml config={{ item }}
  with_dict: "{{ admin_omag_access_services_config | default({}, true) }}"