---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: prep server url base
  set_fact:
    server_base_url: "{{ admin_omag_server_config[config].url }}/open-metadata/admin-services/users/{{ admin_omag_server_config[config].user }}/servers/{{ config }}"

- name: make sure server is reachable
  wait_for:
    host: "{{ app_host }}"
    port: "{{ app_port }}"
    state: started         
    delay: 0               
    timeout: 30        

- name: Start OMAG platform server {{ config }}
  uri:
    url: "{{ server_base_url }}/instance"
    method: POST
    headers:
      Content-Type: application/json
    validate_certs: no
  register: response

- name: Server reponse
  debug:
    var: response

- name: Verify startup
  fail:
    msg: Startup failed, see debug.
  when: response.json.relatedHTTPCode != 200