---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: get application {{ app_name }} cacerts
  copy:
    src: "{{ playbook_dir }}/{{ java_cacerts }}/cacerts"
    dest: "{{ app_keystore_dir }}/cacerts"
    mode: '0400'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    decrypt: true
  when: app_cacerts_password | default(false, true)
  notify: "restart app service"

- name: get application {{ app_name }} keystore
  copy:
    src: "{{ item }}"
    dest: "{{ app_keystore_dir }}/"
    mode: '0400'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    decrypt: true
  with_fileglob: "{{ playbook_dir }}/{{ app_configs_dir }}/{{ app_name }}/{{ inventory_hostname }}/keystore/*"
  when: app_keystore_password | default(false, true)
  notify: "restart app service"

- name: "configure app {{ app_name }}"
  block:
    - name: "include extra vars for app {{ app_name }} configs"
      include_vars:
        file: "{{ playbook_dir }}/{{ app_configs_dir }}/{{ app_name }}/{{ inventory_hostname }}/conf/{{ item }}.yml"
        name: "{{ item | replace('.','_') }}"
      with_items: "{{ app_configs_extra_vars | default([], true) }}"

    - name: "configs for app {{ app_name }}"
      template:
        src: "{{ playbook_dir }}/{{ app_configs_dir }}/{{ app_name }}/{{ inventory_hostname }}/conf/{{ item.key }}.j2"
        dest: "{{ app_config_dir }}/{{ item.key }}"
        mode: "0440"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
      with_dict: "{{ app_configs | default({}, true) }}"
      when: ( item.value.state | default('present', true) ) == 'present'
      notify: restart app service

    - name: "cleanup configs for {{ app_name }}"
      file: path="{{ app_config_dir }}/{{ item.key }}" state=absent
      with_dict: "{{ app_configs | default({}, true) }}"
      when:  ( item.value.state | default('present', true) ) == 'absent'
      notify: restart app service
  when: app_configs | default(false, true)

- name: remove old app config folder
  file:
    path: "{{ app_work_dir }}/config"
    state: absent
