---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: create an empty extra_libs_list
  set_fact:
    extra_libs_list: []

# - name: building extra libs list for cleanup
#   set_fact:
#     extra_libs_list: "{{ \
#       extra_libs_list \
#       + [ item.key \
#       ~ ( ( '-' ~ item.value['version'] ) if item.value['version']|default(false, true) else '' ) \
#       ~ ( ( '-' ~ item.value['suffix'] ) if item.value['suffix']|default(false, true) else '' ) \ 
#       ~ '.' ~ item.value.type|default('jar') ] }}"
#   with_dict: "{{ app_extra_libs | default({}, true) }}"

- name: building extra libs list for cleanup
  set_fact:
    extra_libs_list: "{{ \
      extra_libs_list \
      + [ item.key \
      ~ ( ( '-' ~ item.value['suffix'] ) if item.value['suffix']|default(false, true) else '' ) \ 
      ~ '.' ~ item.value.type|default('jar') ] }}"
  with_dict: "{{ app_extra_libs | default({}, true) }}"

- name: debug extra_libs_list
  debug: var=extra_libs_list
  tags:
    - egeria-debug

- name: list of local app extra libs
  shell: "ls -1 {{ app_libs_dir }}"
  register: lib_folder_content

- name: debug of list local app extra libs
  debug: var=lib_folder_content.stdout_lines
  tags:
    - egeria-debug  

- name: removal of unmanaged libs
  file: path="{{ app_libs_dir }}/{{ item }}" state=absent
  with_items: "{{ lib_folder_content.stdout_lines }}"
  when: item not in extra_libs_list
  notify: "restart app service"
