---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- debug:
    msg: removing application "{{ app_name }}"
- systemd:
    name: "{{ app_name }}"
    state: stopped
  register: appservice
- name: remove conf
  file: path=/etc/systemd/system/{{ app_name }}.service state=absent
  when: appservice.state == 'stopped'
- name: clean application files
  file: path={{ home_dir }}/{{ app_name }} state=absent
- name: clean application log files
  file: path=/var/log/{{ app_name }} state=absent