---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: "set lib {{ item.key }} version suffix"
  set_fact:
    # lib_version_suffix: "{{ ( '-' ~ item.value.suffix ) if item.value.suffix|default(false, true) else '' }}"
    lib_version_suffix: "{{ ( item.value.suffix ) if item.value.suffix|default(false, true) else '' }}"
    local_source: "{{ atr_artifactory_base is search('file://') }}"

- name: "debug version suffix for lib {{ item.key }}"
  debug: var=lib_version_suffix
  tags:
    - egeria-debug

- name: set lib_full_name variables
  set_fact:
    # lib_full_name: "{{ item.key }}-{{ item.value.version ~ lib_version_suffix }}.{{ item.value.type|default('jar', true) }}"
    lib_full_name: "{{ item.key }}-{{ lib_version_suffix }}.{{ item.value.type|default('jar', true) }}"    

- name: set facts for extra_lib
  set_fact:
    lib_path: "{{ app_libs_dir ~ '/' ~ lib_full_name }}"
    full_path: "{{ atr_artifactory_base }}/{{ atr_repository }}/{{ atr_groupId }}/{{ item.key }}/{{ item.value.version }}/{{ lib_full_name }}"
    reg_download_extra_lib:
    lib_cleanup:

- name: upload local artifact for lib item
  copy:
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0440'  
    dest: "{{ lib_path }}"
    src: "{{ full_path | urlsplit('path') }}"
    force: "{{ app_force_replace | default('no', true) }}"  
  register: reg_download_extra_lib
  when: local_source
  notify:
    - restart app service

- name: "download lib {{ item.key }} for app {{ app_name }}"
  get_url:
    url: "{{ atr_artifactory_base }}/{{ atr_repository }}/{{ atr_groupId }}/{{ item.key }}/{{ item.value.version }}/{{ lib_full_name }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0400"
    timeout: "{{ atr_download_timeout }}"
    headers: "{{ atr_get_url_headers_str if ansible_version.full is version('2.6', '<') else atr_get_url_headers_dict }}"
    validate_certs: "{{ atr_validate_certs }}"
    tmp_dest: "{{ app_tmp_dir }}"
    dest: "{{ lib_path }}"
    force: "{{ app_force_replace | default('no', true) }}"
  register: reg_download_extra_lib
  when: not local_source
  notify:
    - "restart app service"

- name: "debug download of extra_lib {{ item.key }}"
  debug: var=reg_download_extra_lib
  tags:
    - egeria-debug
