---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: debug
  debug: var=app_name
  tags:
    - egeria-debug

- name: "download main app for {{ app_name }}"
  include: download-app.yml
  tags:
    - "download"

- name: "apply configs for app {{ app_name }}"
  include: app-configs.yml
  tags:
    - "app-configs"

- name: "cleanup extra libs for {{ app_name }} bypass"
  shell: /bin/true
  register: libs_cleanup_bypass

- name: "cleanup extra libs for {{ app_name }}"
  shell: "rm -f {{ app_libs_dir }}/*"
  when: "libs_cleanup_bypass is not defined"
  tags:
    - "cleanup-extra-libs"

- name: "download extra libs for {{ app_name }}"
  include: manage-extra-libs.yml
  tags:
    - "download-extra-libs"

- name: "install systemctl service unit for {{ app_name }}"
  include: service.yml
  tags:
    - "install-service"
