---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: manage-extra-libs
  debug: var=app_extra_libs
  tags:
    - egeria-debug

- name: manage app extra libs
  include_tasks: download-extra-lib.yml
  with_dict: "{{ app_extra_libs | default({}, true) }}"
  when: item.value.version is defined and item.value.dummy is not defined

- name: cleanup libs folder
  include: cleanup-libs-folder.yml
