---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: "install {{ app_name }} service"
  template:
    src: app_service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    group: root
    mode: '0640'
  notify:
    - systemctl daemon-reload app
    - restart app service
  when: "app_is_downloaded is defined"
