---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: 'systemctl daemon-reload app'
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    daemon_reload: yes

- name: 'start app service'
  systemd:
    name: "{{ app_name }}"
    state: started

- name: 'stop app service'
  systemd:
    name: "{{ app_name }}"
    state: stop

- name: 'restart app service'
  systemd:
    name: "{{ app_name }}"
    state: restarted
