# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: atlas-service
  name: {{ include "myapp.fullname" . }}-atlas-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 21000
      targetPort: 21000
      nodePort: {{ .Values.service.nodeport.atlas }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: atlas-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-atlas
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: atlas-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: atlas-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: atlas-service
    spec:
      containers:
        - name: apache-atlas
          image: "{{ if (.Values.image.atlas.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.atlas.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.atlas.repository | default .Values.imageDefaults.repository) }}{{ .Values.image.atlas.repository | default .Values.imageDefaults.repository }}/{{ end }}\
                  {{ .Values.image.atlas.name }}\
                  :{{ .Values.image.atlas.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.atlas.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          ports:
            - containerPort: 21000
          livenessProbe:
            httpGet:
              path: /login.jsp
              port: 21000
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /login.jsp
              port: 21000
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources: {}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
      restartPolicy: Always

status: {}
...
