# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "myapp.fullname" . }}-configmap
    labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        helm.sh/chart: {{ include "myapp.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
        ATLAS_ENDPOINT: http://{{ include "myapp.fullname" . }}-atlas-service.default.svc.cluster.local:21000
        EGERIA_ENDPOINT: http://{{ include "myapp.fullname" . }}-egeria-service.default.svc.cluster.local:8080
        IGCPROXY_ENDPOINT: http://{{ include "myapp.fullname" . }}-igcproxy-service.default.svc.cluster.local:8080
        KAFKA_ENDPOINT: {{ .Release.Name }}-cp-kafka.default.svc.cluster.local:9092
        IGC_KAFKA_ENDPOINT: 158.176.66.121:59092
        EGERIA_USER: myuser
        EGERIA_COHORT: coco
        EGERIA_SERVER: myserver
        KAFKA_TOPIC: open-metadata.repository-services.cohort.coco.OMRSTopic
        IGC_USER: isadmin
        IGC_PASSWORD: isadmin



