# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
{{ if .Values.gaian.enabled}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: gaian-service
  annotations:
    {{ if .Values.istio.enabled }}
    sidecar.istio.io/inject: "true"
    {{- end }}
  name: {{ include "myapp.fullname" . }}-gaian-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6414
      targetPort: 6414
      nodePort: {{ .Values.service.nodeport.gaian }}

  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gaian-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-gaian-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: gaian-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: gaian-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: gaian-service

    spec:
      containers:
      - name: {{ .Chart.Name }}-gaian
        image: "{{ if (.Values.image.gaian.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.gaian.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                {{ if (.Values.image.gaian.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.gaian.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                {{ .Values.image.gaian.name }}\
                :{{ .Values.image.gaian.tag | default .Values.imageDefaults.tag }}"
        imagePullPolicy: {{ .Values.image.gaian.pullPolicy | default .Values.imageDefaults.pullPolicy }}
        ports:
        - containerPort: 6414
        resources: {}
      restartPolicy: Always
status: {}
{{ end }}
