# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
{{ if .Values.ibmigc.enabled }}
# Only deploy any of this if IGC is enabled
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ibm-igc-service
  annotations:
    {{ if .Values.istio.enabled }}
    sidecar.istio.io/inject: "true"
    {{- end }}
  name: {{ include "myapp.fullname" . }}-ibm-igc-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodeport.igcproxy }}
{{ if .Values.ibmigc.internal.enabled }}
# Only expose web and kafka ports if we are using a cluster-internal IGC
    - name: web
      port: 9446
      targetPort: 9446
      nodePort: {{ .Values.service.nodeport.ibmigc }}
    - name: kafka
      port: 59092
      targetPort: 59092
      nodePort: {{ .Values.service.nodeport.ibmigc_kafka }}
{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ibm-igc-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-ibm-igc
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ibm-igc-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ibm-igc-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ibm-igc-service
    spec:
{{ if .Values.ibmigc.internal.enabled }}
# Fix the hostname to what the image requires of itself and define the secrets to use
# for pulling the container image from a private repository
      hostname: infosvr
      imagePullSecrets:
        - name: regcred
{{ else }}
# When re-using a pre-existing IGC environment, ensure the IP and hostname of the external IGC
# resource are resolve-able
      hostAliases:
        - ip: {{ .Values.ibmigc.external.ip | quote }}
          hostnames:
            - {{ .Values.ibmigc.external.hostname }}
{{ end }}
# In all cases, we need the egeria-connector-ibm-information-server repository's connector to proxy between IGC and OMRS
      volumes:
        - name: egeria-igc-connector-volume
          emptyDir: {}
{{ if .Values.ibmigc.internal.enabled }}
{{ if .Values.localRepo.use }}
# If we are using a local repository, mount the samples from there
        - name: egeria-samples-volume
          hostPath:
            path: {{ .Values.localRepo.location }}
            type: Directory
{{ else }}
# Otherwise we'll git-pull the samples from master
        - name: egeria-samples-volume
          emptyDir: {}
{{ end }}
{{ end }}
      initContainers:
# TODO: Eventually replace the temporary release retrieval below with a package-managed retrieval mechanism
        - name: init-connector
          image: "{{ if (.Values.image.configure.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.configure.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.configure.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.configure.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.configure.name }}\
                  :{{ .Values.image.configure.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.configure.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - >
                cd /opt/egeria/connectors &&
                wget https://odpi.jfrog.io/odpi/egeria-snapshot-local/org/odpi/egeria/egeria-connector-ibm-information-server-package/1.2-SNAPSHOT/egeria-connector-ibm-information-server-package-1.2-SNAPSHOT.jar
          volumeMounts:
            - mountPath: /opt/egeria/connectors
              name: egeria-igc-connector-volume
{{ if and .Values.ibmigc.internal.enabled (not .Values.localRepo.use) }}
# If we are using a cluster-internal IGC, stand up both the IGC container and the proxy, embedding the Ansible
# playbooks for loading sample metadata at runtime within the IGC container
        - name: init-samples
          image: "{{ if (.Values.image.configure.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.configure.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.configure.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.configure.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.configure.name }}\
                  :{{ .Values.image.configure.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.configure.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - >
                cd /opt/egeria/samples &&
                git init . &&
                git remote add origin https://github.com/odpi/egeria.git &&
                git config core.sparsecheckout true &&
                echo 'open-metadata-resources/open-metadata-deployment/sample-data/*' >> .git/info/sparse-checkout &&
                git pull --depth=1 origin master
          volumeMounts:
            - mountPath: /opt/egeria/samples
              name: egeria-samples-volume
{{ end }}
      containers:
        - name: proxy
          image: "{{ if (.Values.image.egeria.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.egeria.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.egeria.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.egeria.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.egeria.name }}\
                  :{{ .Values.image.egeria.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.egeria.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          env:
            - name: "LOADER_PATH"
              value: "/opt/egeria/connectors"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources: {}
          volumeMounts:
            - mountPath: /opt/egeria/connectors
              name: egeria-igc-connector-volume
              readOnly: true
{{ if .Values.ibmigc.internal.enabled }}
        - name: ibm-igc
          image: "{{ if (.Values.image.ibmigc.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.ibmigc.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.ibmigc.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.ibmigc.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.ibmigc.name }}\
                  :{{ .Values.image.ibmigc.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.ibmigc.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["IPC_OWNER"]
          ports:
            - containerPort: 9446
            - containerPort: 52181
            - containerPort: 59092
          livenessProbe:
            httpGet:
              path: /ibm/iis/launchpad
              port: 9446
              scheme: "HTTPS"
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /ibm/iis/launchpad
              port: 9446
              scheme: "HTTPS"
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources: {}
          volumeMounts:
            - mountPath: /opt/egeria/samples
              name: egeria-samples-volume
#      hostIPC: true   # try without this setting to reduce potential risks to host system
{{ end }}

status: {}
...
{{ end }}
