# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-kafka-monitor
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: kafka-monitor-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kafka-monitor-deployment

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: kafka-monitor-deployment

    spec:
      containers:
        - name: {{ include "myapp.fullname" . }}-kafka-monitor
          image: "{{ if (.Values.image.kafkamonitor.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.kafkamonitor.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.kafkamonitor.repository | default .Values.imageDefaults.repository) }}{{ .Values.image.kafkamonitor.repository | default .Values.imageDefaults.repository }}/{{ end }}\
                  {{ .Values.image.kafkamonitor.name }}\
                  :{{ .Values.image.kafkamonitor.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.kafkamonitor.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          resources: {}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
      restartPolicy: Always
status: {}
