# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-ldapinit-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ldapinit-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ldapinit-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ldapinit-service

    spec:
      containers:
      - image: "{{ .Values.image.ldapinit.repository }}:{{ .Values.image.ldapinit.tag }}"
        ImagePullPolicy: "{{ .Values.image.ldapinit.pullPolicy }}"
        name: {{ include "myapp.fullname" . }}-ldapinit
        resources: {}
        envFrom:
        - configMapRef:
            name: {{ include "myapp.fullname" . }}-configmap
      restartPolicy: Always
status: {}
