# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-omrsmonitor-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: omrsmonitor-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: omrsmonitor-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: omrsmonitor-service

    spec:
      containers:
      - image: "{{ .Values.image.omrsmonitor.repository }}:{{ .Values.image.omrsmonitor.tag }}"
        imagePullPolicy: {{ .Values.image.omrsmonitor.pullPolicy }}
        name: {{ include "myapp.fullname" . }}-omrsmonitor
        ports:
        - containerPort: 58080
        resources: {}
        restartPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ include "myapp.fullname" . }}-configmap
status: {}
