# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgresql-service

  name: {{ include "myapp.fullname" . }}-postgresql-service

spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "postgresql"
    port: 5432
    targetPort: 5432
    nodePort: {{ .Values.service.nodeport.postgresql }}
  - name: "postgresql-ssh"
    port: 22
    targetPort: 22
    #nodePort
    # We don't want to expose this with nodeport ( TODO : move to separate service definition )

  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-service
