---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-postgresql-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgresql-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgresql-service

    spec:
      hostAliases:
        - ip: "{{ .Values.igc.host }}"
          hostnames:
          - "{{ .Values.igc.hostname }}"
      containers:
      - image: "{{ .Values.image.postgresql.repository }}:{{ .Values.image.postgresql.tag }}"
        ImagePullPolicy: "{{ .Values.image.postgresql.pullPolicy }}"
        name: {{ include "myapp.fullname" . }}-postgresql
        env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ include "myapp.fullname" . }}-configmap
                key: POSTGRESQL_PASSWORD
        ports:
        - containerPort: 5432
        - containerPort: 22
        resources: {}
        restartPolicy: Always
      - image: "{{ .Values.image.postgresqlinit.repository }}:{{ .Values.image.postgresqlinit.tag }}"
        name: {{ include "myapp.fullname" . }}-postgresqlinit
        ImagePullPolicy: "{{ .Values.image.postgresqlinit.pullPolicy }}"
        envFrom:
        - configMapRef:
           name: {{ include "myapp.fullname" . }}-configmap
        resources: {}
status: {}
