# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
{{ if or .Values.postgresql.enabled .Values.ranger.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgresql-service
  annotations:
  {{ if .Values.istio.enabled }}
    sidecar.istio.io/inject: "true"
  {{- end }}
  name: {{ include "myapp.fullname" . }}-postgresql-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.service.nodeport.postgresql }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgresql-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgresql-service
    spec:
      containers:
        - name: postgresql
          image: "{{ if (.Values.image.postgresql.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.postgresql.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.postgresql.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.postgresql.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.postgresql.name }}\
                  :{{ .Values.image.postgresql.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.postgresql.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp.fullname" . }}-configmap
                  key: POSTGRESQL_PASSWORD
          args:
            - "-i"
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always

status: {}
{{ end }}
