---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: OMAG installation cleanup
  hosts: "{{ target }}"
  serial: 1
  become: yes
  become_user: root
  tasks:
    - include_role:
        name: egeria-omag-server
        tasks_from: cleanup-server
