---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: OMAG installation
  hosts: "{{ target }}"
  serial: 1
  become: yes
  become_user: root
  roles:
    - egeria-omag-server
  tags:
    - install

- name: OMAG administration
  hosts: "{{ target }}"
  serial: 1
  become: yes
  become_user: root
  roles:
    - egeria-omag-server-admin
  tags:
    - configure

- name: Servers startup
  hosts: "{{ target }}"
  serial: 1
  become: yes
  become_user: root
  tasks:
    - include_role:
        name: egeria-omag-server-admin
        tasks_from: start-servers
  tags:
    - start