# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
---
name: Check documentation links
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
#      - name: Create Issue From File
#        uses: peter-evans/create-issue-from-file@v2
#        with:
#          token: "${{ secrets.GITHUB_TOKEN }}"
#          title: Link Checker Report
#          content-filepath: ./link-checker/out.md
#          labels: documentation, consumability, tidy up
