---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: load CocoPharmaceutical sample metadata
  hosts: all
  any_errors_fatal: true
  vars_files:
    - defaults/main.yml
    - vars/users.yml
    - vars/databases.yml
  tasks:
    - name: load sample data files
      include_tasks: data-files/load.yml
      when: ('ibm-information-server-engine' in group_names)

    - name: load sample metadata
      include_tasks: "metadata/{{ egeria_samples_metadata_backend }}/load.yml"
      when: >
        ('ibm-information-server-repo' in group_names)
        or ('ibm-information-server-engine' in group_names)
        or ('ibm-information-server-domain' in group_names)
