---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: load CocoPharmaceutical sample data
  hosts: egeria-samples-db-host
  any_errors_fatal: true
  vars_files:
    - defaults/main.yml
    - vars/users.yml
    - vars/databases.yml
  tasks:
    - name: load sample data files
      include_tasks: data-files/load.yml

    - name: create sample databases
      include_tasks: "database/{{ egeria_samples_cocopharma_db_type }}/create-databases.yml"

    - name: load sample data to databases
      include_tasks: "database/{{ egeria_samples_cocopharma_db_type }}/load.yml"
