---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: remove CocoPharmaceutical sample metadata
  hosts: all
  any_errors_fatal: true
  vars_files:
    - defaults/main.yml
    - vars/users.yml
    - vars/databases.yml
  tasks:
    - name: remove sample data files
      include_tasks: data-files/remove.yml
      when: ('ibm-information-server-engine' in group_names)

    - name: remove sample metadata
      include_tasks: "metadata/{{ egeria_samples_metadata_backend }}/remove.yml"
